name: Test

on:
  push:
    branches: [ main improve-ci]
  pull_request:
    branches: [ main improve-ci]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - os: windows-latest
            build_type: Release
            cmake_args: ""
            preset: msvc-debug
          - os: ubuntu-latest
            cmake_args: "-DCMAKE_CXX_FLAGS='-Werror=all -Werror=extra'"
            preset: gcc-debug
          - os: ubuntu-latest
            cmake_args: "-DCMAKE_CXX_FLAGS='-fsanitize=address -fsanitize=undefined'"
            preset: gcc-debug
          - os: ubuntu-latest
            cmake_args: "-DCMAKE_CXX_FLAGS='-fsanitize=thread'"
            preset: gcc-debug
          - os: ubuntu-latest
            cmake_args: "-DCMAKE_CXX_STANDARD=98 -DCMAKE_CXX_STANDARD_REQUIRED=on"
            preset: gcc-debug
          - os: ubuntu-latest
            cmake_args: "-DCMAKE_CXX_STANDARD=11 -DCMAKE_CXX_STANDARD_REQUIRED=on"
            preset: gcc-debug
          - os: ubuntu-latest
            cmake_args: "-DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_STANDARD_REQUIRED=on"
            preset: gcc-debug
          - os: ubuntu-latest
            cmake_args: "-DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_STANDARD_REQUIRED=on"
            preset: gcc-debug
          - os: ubuntu-latest
            cmake_args: "-DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=on"
            preset: gcc-debug
          - os: ubuntu-latest
            cmake_args: "-DBUILD_SHARED_LIBS=on"
            preset: gcc-debug
          - os: ubuntu-latest
            cmake_args: "-DCMAKE_CXX_FLAGS='-Werror=all -Werror=extra'"
            preset: clang-debug
          - os: ubuntu-latest
            cmake_args: "-DCMAKE_CXX_FLAGS='-fsanitize=address -fsanitize=undefined'"
            preset: clang-debug
          - os: ubuntu-latest
            cmake_args: "-DCMAKE_CXX_FLAGS='-fsanitize=thread'"
            preset: clang-debug
          - os: ubuntu-latest
            cmake_args: "-DCMAKE_CXX_STANDARD=98 -DCMAKE_CXX_STANDARD_REQUIRED=on"
            preset: clang-debug
          - os: ubuntu-latest
            cmake_args: "-DCMAKE_CXX_STANDARD=11 -DCMAKE_CXX_STANDARD_REQUIRED=on"
            preset: clang-debug
          - os: ubuntu-latest
            cmake_args: "-DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_STANDARD_REQUIRED=on"
            preset: clang-debug
          - os: ubuntu-latest
            cmake_args: "-DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_STANDARD_REQUIRED=on"
            preset: clang-debug
          - os: ubuntu-latest
            cmake_args: "-DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=on"
            preset: clang-debug
          - os: ubuntu-latest
            cmake_args: "-DBUILD_SHARED_LIBS=on"
            preset: clang-debug
          - os: macos-latest
            cmake_args: ""
            preset: clang-debug

    steps:
    - uses: actions/checkout@v3
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Setup MSVC
      if: startsWith(matrix.os, 'windows')
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64

    - name: Configure CMake
      run: cmake --preset ${{ matrix.preset }} -DBUILD_TESTING=on ${{ matrix.cmake_args }}

    - name: Build
      run: cmake --build --preset ${{ matrix.preset }}

    - name: Test
      run: ctest --preset ${{ matrix.preset }}
